### ISSUE TITLE
Blank rendering by version 0.19.0

### ISSUE THREAD

**Issue by escreven** [bmpenuelas/waveform-render-vscode#16]
When I execute "Waveform Render: Draw" using version 0.19.0 of the extension in VS Code 1.73.1 the result is a blank rendering.  After downgrading to version 0.18.0, the rendering is as expected.

**Comment by deermiya** [comment]
me too

**Comment by Donlon** [comment]
There are the same issue on my VS Code 1.73.1.  After opening the Dev Tools, I found that there are resources failed to load due to `net::ERR_UNKNOWN_URL_SCHEME` error, and this is probably the root cause of the issue.

<img width="939" src="https://user-images.githubusercontent.com/4056887/202971547-15f9f401-a0ba-42cc-8075-8d5fb26a01c9.png">

**Comment by donlon** [comment]
There is the same issue on my VS Code 1.73.1 with plugin of version 0.19.0.  After opening the Dev Tools, I found that there are resources failed to load due to `net::ERR_UNKNOWN_URL_SCHEME` error.

<img width="939" src="https://user-images.githubusercontent.com/4056887/202971547-15f9f401-a0ba-42cc-8075-8d5fb26a01c9.png">

**Comment by lionheart117** [comment]
the same issue I came cross

**Comment by bmpenuelas** [comment]
New release including fix has been published to the marketplace, thanks!
